-- Remove the inncesary table name
create or replace TRIGGER "IFF_TGR_TABLES_AI" AFTER INSERT ON IFF_TABLES
FOR EACH ROW
BEGIN
IFF_SP_INSERT_TABLE_COLUMNS(:new.TABLE_ID);
IFF_SP_INSERT_MENU_ITEMS(:new.TABLE_NAME);
END;
/